// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipjqxuqltliafyjdtrti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwanF4dXFsdGxpYWZ5amR0cnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzY5MDksImV4cCI6MjA1NzYxMjkwOX0.V_gZ772gJR2-Zgl4ckbRgcfjITaxIarZNMy7Rrt2HLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);